### ISSUE TITLE
LORA edit does not change model's answers

### ISSUE THREAD

**Issue by nrosen1** [zjunlp/EasyEdit#187] opened 2024-02-29 09:57 UTC
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/2dd0ea29-b686-4ebc-a98b-28a3be10354f)
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/602999fb-a485-48b5-8f4a-385ec7ae8945)
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/72ce6330-b131-4b10-a1ab-d8eeccb2200e)
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/047c5050-39e9-445c-9f54-48a5302e9423)
tried to generate() multiple time and answer stays Volvo and not Volkswagen.
tried on several other samples from zsre_mend_eval_portability_gpt4.json

**Comment by XeeKee** [comment] 2024-02-29 11:44
Hello, I'm sorry I am unable to reproduce your issue. Could you please provide your code so that I can assist you better in resolving the problem? By the way, you can check if you have set keep_original_weight=False in your editor.edit() method.

**Comment by nrosen1** [comment] 2024-02-29 11:52
@XeeKee You are right, keep_original_weight=False solved it and edit works now, thanks!!
one question - how can i access the original non-peft model with this flag=false?

**Comment by nrosen1** [comment] 2024-02-29 11:56
@XeeKee that's a nice solution, thanks!
the thing is i want both objects in memory to iterate over the dataset and generate both answers: orig.gen() + edited.gen()
is there an object i can access to do so?

**Comment by XeeKee** [comment] 2024-02-29 12:01
I'm sorry, I don't have any good ideas at the moment on how to implement your request outside of the editor function. I think you might be able to achieve your goal by making modifications inside the editor function.

**Closed** 2024-02-29 12:06 UTC

**Comment by nrosen1** [comment] 2024-02-29 12:10
thanks again!
