### ISSUE TITLE
data issues

### ISSUE THREAD

**Issue by icoderzqliu** [zjunlp/EasyEdit#11] opened 2023-08-24 14:41 UTC
Hello, I am confused about some files in EasyEdit.

1. The file downloaded from the link provided in README.md is called "data", and the file downloaded from examples is called "editing-data". What is the difference between these two files?

2. Both the README in the repo and the README in examples mention placing data in the "./data" folder and the model in the "./hugging_cache" folder. Do I need to create these folders separately in both the repo and examples directories?

3. Should the entry file be edit.py or examples/run_zsre_llama2.py and what's the difference?

4. It would be helpful if you could provide an overview and explanation of the file structure of the entire repo, similar to the following structure.
```
editing-data
├── counterfact
│   ├── counterfact-original-edit.json
│   ├── counterfact-original-train.json
│   └── counterfact-original-val.json
├── locality
│   ├── Commonsense Task
│   │   ├── piqa_valid-labels.lst
│   │   └── piqa_valid.jsonl
│   ├── Distracting Neighbor
│   │   └── counterfact_distracting_neighbor.json
│   └── Other Attribution
│       └── counterfact_other_attribution.json
├── portability
│   ├── Inverse Relation
│   │   └── zsre_inverse_relation.json
│   ├── One Hop
│   │   ├── counterfact_portability_gpt4.json
│   │   └── zsre_mend_eval_portability_gpt4.json
│   └── Subject Replace
│       ├── counterfact_subject_replace.json
│       └── zsre_subject_replace.json
└── zsre
    ├── zsre_mend_eval.json
    └── zsre_mend_train_10000.json
```
Thank you very much~

**Comment by pengzju** [comment] 2023-08-24 15:48
- Problem 1: We are sorry for uploading inconsistent data due to our negligence. The consideration for uploading `data` is that training may require a relatively large amount of data, so we upload `zsre_mend_train.json`. We will merge the two, you only need to focus on **`editing-data`**. Now we have updated our README
- Problem 2: You just need to create `./data` and `./hugging_cache` **in the current directory of the folder you are running**.
- Problem 3: `edit.py` is the script we used to test (as a reference for you to employ this tool). If you want to reproduce the details on llama2, you can use `example` module
- Problem 4: 
```text
EasyEdit
├── easyeditor
│   ├── dataset #load dataset 
│   ├── editors # editor for LM(apply editing method)
│   └── evaluate # evaluation for editing process
│   └── models # editing methods
│   └── trainer # trainer for SERAC and MEND
├── examples # examples to elaborate the basic usage of EasyEdit.(reproducing results on llama2)
├── hparams # yaml configuration for editing method
```

You can refer to the paper for more details https://arxiv.org/abs/2308.07269

**Comment by pengzju** [comment] 2023-08-24 15:53
If your problem has been resolved, please help close this issue.

**Closed** 2023-08-25 03:44 UTC
Labels: question
