### ISSUE TITLE
Import EasyEdit caused "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by peixin-lin** [zjunlp/EasyEdit#19] opened 2023-09-11 01:42 UTC
```
git clone https://github.com/zjunlp/EasyEdit.git
conda create -n EasyEdit python=3.9.7
...
pip install -r  requirements.txt
```
Following the instructions above in README, after the environments  have been set up, I just tried `from easyeditor import MENDHyperParams` and it caused a segfault: "Segmentation fault (core dumped)". And I also tried `import torch`, the same error happened. Importing other packages like transformers won't caused the segfault.

Is there any way to work around this problem? Please advice.

**Comment by pengzju** [comment] 2023-09-11 03:40
> ```
> git clone https://github.com/zjunlp/EasyEdit.git
> conda create -n EasyEdit python=3.9.7
> ...
> pip install -r  requirements.txt
> ```
> 
> Following the instructions above in README, after the environments have been set up, I just tried `from easyeditor import MENDHyperParams` and it caused a segfault: "Segmentation fault (core dumped)". And I also tried `import torch`, the same error happened. Importing other packages like transformers won't caused the segfault.
> 
> Is there any way to work around this problem? Please advice.

Did you run the following command?
like:
```
source activate
conda activate EasyEdit
```
`Segmentation fault (core dumped)` mostly cause by improper memory operations.

**Comment by peixin-lin** [comment] 2023-09-11 09:30
> > ```
> > git clone https://github.com/zjunlp/EasyEdit.git
> > conda create -n EasyEdit python=3.9.7
> > ...
> > pip install -r  requirements.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Following the instructions above in README, after the environments have been set up, I just tried `from easyeditor import MENDHyperParams` and it caused a segfault: "Segmentation fault (core dumped)". And I also tried `import torch`, the same error happened. Importing other packages like transformers won't caused the segfault.
> > Is there any way to work around this problem? Please advice.
> 
> Did you run the following command? like:
> 
> ```
> source activate
> conda activate EasyEdit
> ```
> 
> `Segmentation fault (core dumped)` mostly cause by improper memory operations.

Yes, I did. The segmentation fault happened in the EasyEdit virtual env.
How can I find out what kind of improper memory operations lead to this segfault? All I did was importing. 
Please advice.

**Comment by pengzju** [comment] 2023-09-11 11:22
I cannot reproduce your problem, please check your local computer configuration
<img width="1005" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/63391142/b40ea386-651f-492d-94c2-19890e114325">

**Comment by pengzju** [comment] 2023-09-12 05:33
If your problem has been resolved, please help close this issue.

**Closed** 2023-09-13 07:24 UTC
Labels: question

**Comment by HamLaertes** [comment] 2023-09-13 12:46
Hi, I met the same problem, and I have solved it by setting LD_LIBRARY_PATH="".
Hoping the solution work on your machine.
